
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__dbus_saf_proxy_hpp__PROXY_MARSHAL_H
#define __dbusxx__dbus_saf_proxy_hpp__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace xmpp {

class saf_proxy
: public ::DBus::InterfaceProxy
{
public:

    saf_proxy()
    : ::DBus::InterfaceProxy("xmpp.saf")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    void Quit()
    {
        ::DBus::CallMessage call;
        call.member("Quit");
        ::DBus::Message ret = invoke_method (call);
    }

    void SendMsg(const std::string& recipient, const std::string& msg)
    {
        ::DBus::CallMessage call;
        ::DBus::MessageIter wi = call.writer();

        wi << recipient;
        wi << msg;
        call.member("SendMsg");
        ::DBus::Message ret = invoke_method (call);
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} 
#endif //__dbusxx__dbus_saf_proxy_hpp__PROXY_MARSHAL_H
